// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SLK.XClinic.WebHost
{
    public static class AutoClass
    {
        public static string MajorMinor = "1.25";
		public static string FullVersion = "1.25.1008";
        public static string BuildName = "#nightly";
    }
}
